### ISSUE TITLE
issue when trying tcp attack

### ISSUE THREAD

**Issue by BlackXS** [entynetproject/quack#13]
i used the syntax in your page but i got this in the outcome

Traceback (most recent call last):
  File "./quack", line 146, in <module>
    main()
  File "./quack", line 91, in main
    TCP_ATTACK(threads, time, target)
  File "/root/quack/tools/L4/tcp.py", line 35, in TCP_ATTACK
    target_port = int(target.split(":")[1])
IndexError: list index out of range

**Comment by enty8080** [comment]
You should to define port

**Comment by enty8080** [comment]
Please rtfd (readme.md)
