### ISSUE TITLE
--tool HTTP 

### ISSUE THREAD

**Issue by pesertakursustm** [entynetproject/quack#8]
Traceback (most recent call last):
  File "./quack", line 127, in <module>
    main()
  File "./quack", line 103, in main
    HTTP_ATTACK(threads, time, target)
  File "/root/quack/tools/L7/http.py", line 38, in HTTP_ATTACK
    if ipTools.isCloudFlare(target):
  File "/root/quack/tools/ipTools.py", line 39, in isCloudFlare
    if ipaddress.ip_address(origin) in ipaddress.ip_network(ipv4[i]):
  File "/usr/lib/python3.8/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: '<!DOCTYPE html>' does not appear to be an IPv4 or IPv6 network

**Comment by enty8080** [comment]
Send me your command, that caused this exception

**Comment by enty8080** [comment]
You should to enter `url` not `ip` for example:
`quack --tool http --target http://example.com --timeout 10 --threads 10`
